// ============================================================
// DATABASE SEED DATA
// ============================================================
// Sample data for testing and development
// ============================================================

class DatabaseSeeder {
  DatabaseSeeder._();

  // ============================================================
  // STAFF DATA
  // ============================================================
  static final List<Map<String, dynamic>> staffData = [
    {
      'id': 'STAFF001',
      'full_name': 'مدیر سیستم',
      'phone': '09121234567',
      'email': 'admin@gym.com',
      'role': 'ADMIN',
      'username': 'admin',
      'password_hash': 'admin123',
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'STAFF002',
      'full_name': 'احمد رضایی',
      'phone': '09129876543',
      'email': 'ahmad@gym.com',
      'role': 'TRAINER',
      'username': 'trainer1',
      'password_hash': 'trainer123',
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'STAFF003',
      'full_name': 'فاطمه محمدی',
      'phone': '09125554433',
      'email': 'fateme@gym.com',
      'role': 'ACCOUNTANT',
      'username': 'accountant1',
      'password_hash': 'accountant123',
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'STAFF004',
      'full_name': 'سارا احمدی',
      'phone': '09121112233',
      'email': 'sara@gym.com',
      'role': 'RECEPTIONIST',
      'username': 'reception1',
      'password_hash': 'reception123',
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
  ];

  // ============================================================
  // MEMBER DATA
  // ============================================================
  static final List<Map<String, dynamic>> memberData = [
    {
      'id': 'MEM001',
      'full_name': 'علی محمدی',
      'phone': '09121234567',
      'email': 'ali@example.com',
      'gender': 'MALE',
      'birth_date': '1990-05-15',
      'membership_status': 'ACTIVE',
      'membership_type': 'MONTHLY',
      'membership_expiry_date': DateTime.now().add(const Duration(days: 30)).toIso8601String(),
      'outstanding_balance': 0,
      'total_paid': 500000,
      'total_visits': 25,
      'is_active': 1,
      'is_blocked': 0,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'MEM002',
      'full_name': 'رضا احمدی',
      'phone': '09129876543',
      'email': 'reza@example.com',
      'gender': 'MALE',
      'birth_date': '1985-08-20',
      'membership_status': 'ACTIVE',
      'membership_type': 'QUARTERLY',
      'membership_expiry_date': DateTime.now().add(const Duration(days: 60)).toIso8601String(),
      'outstanding_balance': 0,
      'total_paid': 1500000,
      'total_visits': 45,
      'is_active': 1,
      'is_blocked': 0,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'MEM003',
      'full_name': 'سارا کریمی',
      'phone': '09125554433',
      'email': 'sara@example.com',
      'gender': 'FEMALE',
      'birth_date': '1995-03-10',
      'membership_status': 'ACTIVE',
      'membership_type': 'MONTHLY',
      'membership_expiry_date': DateTime.now().add(const Duration(days: 15)).toIso8601String(),
      'outstanding_balance': 200000,
      'total_paid': 300000,
      'total_visits': 18,
      'is_active': 1,
      'is_blocked': 0,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'MEM004',
      'full_name': 'محمد حسینی',
      'phone': '09121112233',
      'email': 'mohammad@example.com',
      'gender': 'MALE',
      'birth_date': '1988-11-25',
      'membership_status': 'EXPIRED',
      'membership_type': 'MONTHLY',
      'membership_expiry_date': DateTime.now().subtract(const Duration(days: 10)).toIso8601String(),
      'outstanding_balance': 500000,
      'total_paid': 200000,
      'total_visits': 30,
      'is_active': 1,
      'is_blocked': 0,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'MEM005',
      'full_name': 'زهرا عباسی',
      'phone': '09123334455',
      'email': 'zahra@example.com',
      'gender': 'FEMALE',
      'birth_date': '1992-07-18',
      'membership_status': 'ACTIVE',
      'membership_type': 'ANNUAL',
      'membership_expiry_date': DateTime.now().add(const Duration(days: 180)).toIso8601String(),
      'outstanding_balance': 0,
      'total_paid': 5000000,
      'total_visits': 120,
      'is_active': 1,
      'is_blocked': 0,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'MEM006',
      'full_name': 'حسن رستمی',
      'phone': '09124445566',
      'email': 'hassan@example.com',
      'gender': 'MALE',
      'birth_date': '1993-01-30',
      'membership_status': 'SUSPENDED',
      'membership_type': 'MONTHLY',
      'membership_expiry_date': DateTime.now().add(const Duration(days: 5)).toIso8601String(),
      'outstanding_balance': 300000,
      'total_paid': 400000,
      'total_visits': 15,
      'is_active': 1,
      'is_blocked': 0,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'MEM007',
      'full_name': 'نیلوفر صادقی',
      'phone': '09126667788',
      'email': 'niloufar@example.com',
      'gender': 'FEMALE',
      'birth_date': '1998-09-12',
      'membership_status': 'ACTIVE',
      'membership_type': 'MONTHLY',
      'membership_expiry_date': DateTime.now().add(const Duration(days: 25)).toIso8601String(),
      'outstanding_balance': 0,
      'total_paid': 600000,
      'total_visits': 22,
      'is_active': 1,
      'is_blocked': 0,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'MEM008',
      'full_name': 'امیر کاظمی',
      'phone': '09128889900',
      'email': 'amir@example.com',
      'gender': 'MALE',
      'birth_date': '1987-04-05',
      'membership_status': 'ACTIVE',
      'membership_type': 'QUARTERLY',
      'membership_expiry_date': DateTime.now().add(const Duration(days: 45)).toIso8601String(),
      'outstanding_balance': 100000,
      'total_paid': 1200000,
      'total_visits': 55,
      'is_active': 1,
      'is_blocked': 0,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'MEM009',
      'full_name': 'مریم نوری',
      'phone': '09127776655',
      'email': 'maryam@example.com',
      'gender': 'FEMALE',
      'birth_date': '1996-12-20',
      'membership_status': 'PENDING',
      'membership_type': 'MONTHLY',
      'membership_expiry_date': DateTime.now().add(const Duration(days: 30)).toIso8601String(),
      'outstanding_balance': 500000,
      'total_paid': 0,
      'total_visits': 0,
      'is_active': 1,
      'is_blocked': 0,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'MEM010',
      'full_name': 'کامران بهرامی',
      'phone': '09129998877',
      'email': 'kamran@example.com',
      'gender': 'MALE',
      'birth_date': '1991-06-08',
      'membership_status': 'ACTIVE',
      'membership_type': 'ANNUAL',
      'membership_expiry_date': DateTime.now().add(const Duration(days: 300)).toIso8601String(),
      'outstanding_balance': 0,
      'total_paid': 8000000,
      'total_visits': 200,
      'is_active': 1,
      'is_blocked': 0,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
  ];

  // ============================================================
  // PRODUCT DATA
  // ============================================================
  static final List<Map<String, dynamic>> productData = [
    {
      'id': 'PROD001',
      'product_name': 'پروتئین شیک',
      'barcode': '6281000000001',
      'category_id': 'CAT001',
      'selling_price': 150000,
      'cost_price': 100000,
      'current_stock': 50,
      'min_stock_level': 10,
      'max_stock_level': 100,
      'unit': 'PIECE',
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'PROD002',
      'product_name': 'آب معدنی',
      'barcode': '6281000000002',
      'category_id': 'CAT002',
      'selling_price': 10000,
      'cost_price': 5000,
      'current_stock': 200,
      'min_stock_level': 50,
      'max_stock_level': 500,
      'unit': 'BOTTLE',
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'PROD003',
      'product_name': 'موز',
      'barcode': '6281000000003',
      'category_id': 'CAT003',
      'selling_price': 25000,
      'cost_price': 15000,
      'current_stock': 30,
      'min_stock_level': 10,
      'max_stock_level': 50,
      'unit': 'PIECE',
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'PROD004',
      'product_name': 'شیر کم‌چرب',
      'barcode': '6281000000004',
      'category_id': 'CAT002',
      'selling_price': 35000,
      'cost_price': 25000,
      'current_stock': 40,
      'min_stock_level': 15,
      'max_stock_level': 100,
      'unit': 'BOTTLE',
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'PROD005',
      'product_name': 'نوار انرژی',
      'barcode': '6281000000005',
      'category_id': 'CAT004',
      'selling_price': 85000,
      'cost_price': 55000,
      'current_stock': 25,
      'min_stock_level': 10,
      'max_stock_level': 50,
      'unit': 'PIECE',
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'PROD006',
      'product_name': 'سالاد سزار',
      'barcode': '6281000000006',
      'category_id': 'CAT005',
      'selling_price': 180000,
      'cost_price': 120000,
      'current_stock': 15,
      'min_stock_level': 5,
      'max_stock_level': 30,
      'unit': 'PIECE',
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'PROD007',
      'product_name': 'قرص ویتامین',
      'barcode': '6281000000007',
      'category_id': 'CAT006',
      'selling_price': 250000,
      'cost_price': 180000,
      'current_stock': 8,
      'min_stock_level': 10,
      'max_stock_level': 50,
      'unit': 'BOX',
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'PROD008',
      'product_name': 'چای سبز',
      'barcode': '6281000000008',
      'category_id': 'CAT002',
      'selling_price': 15000,
      'cost_price': 8000,
      'current_stock': 100,
      'min_stock_level': 30,
      'max_stock_level': 200,
      'unit': 'PIECE',
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
  ];

  // ============================================================
  // CATEGORY DATA
  // ============================================================
  static final List<Map<String, dynamic>> categoryData = [
    {
      'id': 'CAT001',
      'name': 'مکمل‌ها',
      'description': 'مکمل‌های ورزشی و پروتئین',
      'icon': 'fitness_center',
      'color': '#4CAF50',
      'sort_order': 1,
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'CAT002',
      'name': 'نوشیدنی‌ها',
      'description': 'آب، شیر، چای و نوشیدنی‌ها',
      'icon': 'local_drink',
      'color': '#2196F3',
      'sort_order': 2,
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'CAT003',
      'name': 'میوه‌ها',
      'description': 'میوه‌های تازه',
      'icon': 'nutrition',
      'color': '#FF9800',
      'sort_order': 3,
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'CAT004',
      'name': 'تنقلات',
      'description': 'نوار انرژی و تنقلات سالم',
      'icon': 'restaurant',
      'color': '#E91E63',
      'sort_order': 4,
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'CAT005',
      'name': 'غذا',
      'description': 'غذاهای سالم و رژیمی',
      'icon': 'restaurant_menu',
      'color': '#9C27B0',
      'sort_order': 5,
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'CAT006',
      'name': 'دارو و مکمل',
      'description': 'داروها و مکمل‌های بهداشتی',
      'icon': 'medication',
      'color': '#009688',
      'sort_order': 6,
      'is_active': 1,
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
  ];

  // ============================================================
  // PAYMENT DATA
  // ============================================================
  static final List<Map<String, dynamic>> paymentData = [
    {
      'id': 'PAY001',
      'member_id': 'MEM001',
      'amount': 500000,
      'payment_date': DateTime.now().subtract(const Duration(days: 30)).toIso8601String(),
      'payment_type': 'MEMBERSHIP',
      'payment_method': 'CASH',
      'payment_status': 'PAID',
      'description': 'پرداخت عضویت ماهانه',
      'created_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'PAY002',
      'member_id': 'MEM002',
      'amount': 1500000,
      'payment_date': DateTime.now().subtract(const Duration(days: 60)).toIso8601String(),
      'payment_type': 'MEMBERSHIP',
      'payment_method': 'CARD',
      'payment_status': 'PAID',
      'description': 'پرداخت عضویت سه‌ماهه',
      'created_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'PAY003',
      'member_id': 'MEM003',
      'amount': 200000,
      'payment_date': DateTime.now().subtract(const Duration(days: 15)).toIso8601String(),
      'payment_type': 'MEMBERSHIP',
      'payment_method': 'TRANSFER',
      'payment_status': 'PARTIAL',
      'description': 'پرداخت بخشی از عضویت',
      'created_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'PAY004',
      'member_id': 'MEM004',
      'amount': 500000,
      'payment_date': DateTime.now().subtract(const Duration(days: 45)).toIso8601String(),
      'payment_type': 'MEMBERSHIP',
      'payment_method': 'CASH',
      'payment_status': 'OVERDUE',
      'description': 'پرداخت معوق',
      'created_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'PAY005',
      'member_id': 'MEM005',
      'amount': 5000000,
      'payment_date': DateTime.now().subtract(const Duration(days: 365)).toIso8601String(),
      'payment_type': 'MEMBERSHIP',
      'payment_method': 'TRANSFER',
      'payment_status': 'PAID',
      'description': 'پرداخت عضویت سالانه',
      'created_at': DateTime.now().toIso8601String(),
    },
  ];

  // ============================================================
  // TRANSACTION DATA
  // ============================================================
  static final List<Map<String, dynamic>> transactionData = [
    {
      'id': 'TRX001',
      'transaction_number': 'TRX-20240101-001',
      'transaction_type': 'INCOME',
      'category': 'MEMBERSHIP',
      'amount': 500000,
      'description': 'عضویت علی محمدی',
      'transaction_date': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
      'created_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'TRX002',
      'transaction_number': 'TRX-20240101-002',
      'transaction_type': 'INCOME',
      'category': 'PRODUCT_SALES',
      'amount': 150000,
      'description': 'فروش پروتئین شیک',
      'transaction_date': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
      'created_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'TRX003',
      'transaction_number': 'TRX-20240101-003',
      'transaction_type': 'EXPENSE',
      'category': 'SALARY',
      'amount': 15000000,
      'description': 'حقوق ماهانه کارکنان',
      'transaction_date': DateTime.now().subtract(const Duration(days: 5)).toIso8601String(),
      'created_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'TRX004',
      'transaction_number': 'TRX-20240101-004',
      'transaction_type': 'EXPENSE',
      'category': 'RENT',
      'amount': 20000000,
      'description': 'اجاره ماهانه باشگاه',
      'transaction_date': DateTime.now().subtract(const Duration(days: 10)).toIso8601String(),
      'created_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'TRX005',
      'transaction_number': 'TRX-20240101-005',
      'transaction_type': 'INCOME',
      'category': 'TRAINING_SESSIONS',
      'amount': 800000,
      'description': 'هزینه جلسات خصوصی',
      'transaction_date': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
      'created_at': DateTime.now().toIso8601String(),
    },
  ];

  // ============================================================
  // ATTENDANCE DATA
  // ============================================================
  static final List<Map<String, dynamic>> attendanceData = [
    {
      'id': 'ATT001',
      'member_id': 'MEM001',
      'member_name': 'علی محمدی',
      'check_in_time': DateTime.now().subtract(const Duration(hours: 3)).toIso8601String(),
      'check_out_time': DateTime.now().subtract(const Duration(hours: 1)).toIso8601String(),
      'duration_minutes': 120,
      'check_in_method': 'QR_CODE',
      'created_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'ATT002',
      'member_id': 'MEM002',
      'member_name': 'رضا احمدی',
      'check_in_time': DateTime.now().subtract(const Duration(hours: 2)).toIso8601String(),
      'check_out_time': null,
      'duration_minutes': null,
      'check_in_method': 'MANUAL',
      'created_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'ATT003',
      'member_id': 'MEM005',
      'member_name': 'زهرا عباسی',
      'check_in_time': DateTime.now().subtract(const Duration(hours: 4)).toIso8601String(),
      'check_out_time': DateTime.now().subtract(const Duration(hours: 2)).toIso8601String(),
      'duration_minutes': 120,
      'check_in_method': 'FINGERPRINT',
      'created_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'ATT004',
      'member_id': 'MEM007',
      'member_name': 'نیلوفر صادقی',
      'check_in_time': DateTime.now().subtract(const Duration(hours: 1)).toIso8601String(),
      'check_out_time': null,
      'duration_minutes': null,
      'check_in_method': 'MANUAL',
      'created_at': DateTime.now().toIso8601String(),
    },
  ];

  // ============================================================
  // SETTINGS DATA
  // ============================================================
  static final List<Map<String, dynamic>> settingsData = [
    {
      'id': 'SET001',
      'setting_key': 'gym_name',
      'setting_value': 'باشگاه بدنسازی بدن‌ساز',
      'setting_type': 'STRING',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'SET002',
      'setting_key': 'gym_address',
      'setting_value': 'تهران، خیابان ولیعصر، پلاک ۱۲۳',
      'setting_type': 'STRING',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'SET003',
      'setting_key': 'gym_phone',
      'setting_value': '02112345678',
      'setting_type': 'STRING',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'SET004',
      'setting_key': 'currency',
      'setting_value': 'تومان',
      'setting_type': 'STRING',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'SET005',
      'setting_key': 'tax_rate',
      'setting_value': '0.10',
      'setting_type': 'DOUBLE',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
    {
      'id': 'SET006',
      'setting_key': 'max_capacity',
      'setting_value': '100',
      'setting_type': 'INTEGER',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    },
  ];

  // ============================================================
  // METHOD TO GET ALL SEED DATA
  // ============================================================
  static Map<String, List<Map<String, dynamic>>> getAllSeedData() {
    return {
      'staff': staffData,
      'members': memberData,
      'products': productData,
      'categories': categoryData,
      'payments': paymentData,
      'transactions': transactionData,
      'attendance': attendanceData,
      'settings': settingsData,
    };
  }
}